version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garagephp-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=$(DB_NAME)
      - DB_USER=$(DB_USER)
      - DB_PASSWORD=$(DB_PASSWORD)
      - STORAGE_PATH=/var/www/html/storage

  db:
    image: mysql:8.0
    container_name: garagephp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $(DB_NAME)
      MYSQL_USER: $(DB_USER)
      MYSQL_PASSWORD: $(DB_PASSWORD)
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/garagephp.sql:/docker-entrypoint-initdb.d/init.sql
      
volumes:
   db_data:
  
   

  